-- CreateTable
CREATE TABLE "Task" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL,
    "priority" TEXT NOT NULL DEFAULT 'medium',
    "taskType" TEXT NOT NULL DEFAULT 'general',
    "projectId" TEXT NOT NULL,
    "projectName" TEXT NOT NULL,
    "assignees" JSONB NOT NULL DEFAULT '[]',
    "assignedById" TEXT NOT NULL DEFAULT '',
    "assignedByName" TEXT NOT NULL DEFAULT '',
    "reporterId" TEXT NOT NULL DEFAULT '',
    "reporterName" TEXT NOT NULL DEFAULT '',
    "dueDate" TEXT NOT NULL,
    "startDate" TEXT,
    "tags" TEXT[],
    "subtasks" JSONB NOT NULL DEFAULT '[]',
    "comments" JSONB NOT NULL DEFAULT '[]',
    "attachments" JSONB NOT NULL DEFAULT '[]',
    "dependencies" JSONB NOT NULL DEFAULT '[]',
    "timeEntries" JSONB NOT NULL DEFAULT '[]',
    "referenceLinks" JSONB NOT NULL DEFAULT '[]',
    "activityLog" JSONB NOT NULL DEFAULT '[]',
    "estimatedHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "actualHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "isBlocked" BOOLEAN NOT NULL DEFAULT false,
    "isRecurring" BOOLEAN NOT NULL DEFAULT false,
    "recurringPattern" TEXT,
    "customFields" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Task_pkey" PRIMARY KEY ("id")
);
